# Base docker compose, added to by docker-compose.override or docker-compose.prod. See Readme.md

services:
  # PHP & apache container using offical Docker PHP iamge
  web:
    # If pre-built image from docker hub exists then use that (docker pull openenergymonitor/emoncms:latest) if not build container see web/Dockerflile
    image: openenergymonitor/emoncms:latest
    build: web/.
    volumes:
    - type: bind
      source: /mnt/emoncms/phpfiwa
      target: /var/opt/emoncms/phpfiwa
      bind:
        create_host_path: true
    - type: bind
      source: /mnt/emoncms/phpfina
      target: /var/opt/emoncms/phpfina
      bind:
        create_host_path: true
    - type: bind
      source: /etc/localtime
      target: /etc/localtime
      read_only: true
      bind:
        create_host_path: true
    links:
      - db
      - redis

  db:
    image: mariadb:11.0
    environment:
      - "MYSQL_HOST=localhost"
      - "MARIADB_AUTO_UPGRADE=1"
      - "MARIADB_INITDB_SKIP_TZINFO=1"
    ports:
      # Expose Emoncms to the world on port 80
      - 3306:3306
    volumes:
    - type: bind
      source: /mnt/emoncms/db-data
      target: /var/lib/mysql
      bind:
        create_host_path: true
    - type: bind
      source: /etc/localtime
      target: /etc/localtime
      read_only: true
      bind:
        create_host_path: true
    logging:
      driver: json-file
      options:
        max-size: "10m"

  redis:
    image: redis:7.0
    volumes:
    - type: bind
      source: /mnt/emoncms/redis-data
      target: /data
      bind:
        create_host_path: true
    - type: bind
      source: /etc/localtime
      target: /etc/localtime
      read_only: true
      bind:
        create_host_path: true
    logging:
      driver: json-file
      options:
        max-size: "10m"
          
